modLoader="javafml"
loaderVersion="[51,)"
license="MIT License"

issueTrackerURL="https://github.com/SpongePowered/Sponge/issues"


[[mods]]
modId="spongeforge"
version="{{ version }}"
displayName="SpongeForge"
displayTest="IGNORE_SERVER_VERSION"
credits="SpongePowered and Contributors"
authors="SpongePowered"
description = "{{ description }}"

[[dependencies.spongeforge]]
modId="forge"
mandatory=true
versionRange="[51,)"
ordering="AFTER"
side="BOTH"

[[dependencies.spongeforge]]
modId="sponge"
mandatory=true
versionRange="[{{ version }}]"
ordering="AFTER"
side="BOTH"


[[mods]]
modId="sponge"
version="{{ version }}"
displayName="Sponge"
displayTest="IGNORE_SERVER_VERSION"
credits="SpongePowered and Contributors"
authors="SpongePowered"
description="The SpongeAPI implementation targeting vanilla Minecraft and 3rd party platforms"

[[dependencies.sponge]]
modId="spongeapi"
mandatory=true
versionRange="[12.0.0,)"
ordering="AFTER"
side="BOTH"


[[mods]]
modId="spongeapi"
version="12.0.0"
displayName="SpongeAPI"
displayTest="IGNORE_SERVER_VERSION"
credits="SpongePowered and Contributors"
authors="SpongePowered"
description="A Minecraft plugin API"
